const express = require('express');
const app = express();
const path = require('path');
const nodemailer = require('nodemailer')
let bodyParser = require('body-parser')

require('dotenv').config()


const PORT = process.env.PORT || 3000;


let urlencodedParser = bodyParser.urlencoded({ extended: false})


//set static folder
app.use(express.static(path.join(__dirname, 'public')))


app.post('/send',urlencodedParser, (req, res)=>{
    console.log(req.body)

    const output = `
        <p>You have a new contact reques</p>

        <h3>Contact Details</h3>

        <ul>
        <li>Name: ${req.body.fname}</li>
        <li>Email: ${req.body.email}</li>
        </ul>

        <h3>Message</h3>

        
        <p>${req.body.content}</p>
    `


      // let transporter = nodemailer.createTransport({
      //   service: 'gmail',
      //   auth: {
      //     user: process.env.EMAIL,
      //     pass: process.env.PASSWORD
      //   }
      // });

      // let transporter = nodemailer.createTransport({
      //   host: 'smtp.mailtrap.io',
      //   port: '587 ',
      //   secure: false,
      //   tls: 'STARTTLS',
      //   requireTLS:true,//this parameter solved problem for me
      //   auth: {
      //     user: '85395e426e7a79L',
      //     pass: '88d3ccb82d94ba'
      //   }
      // })
    
      // // send mail with defined transport object
      // let info = {
      //   from: 'pluralplu77@gmail.com', // sender address
      //   to: 'padarko99@gmail.com', // list of receivers
      //   subject: "Resume", // Subject line
      //   text: "reached out on resume", // plain text body
      //   html: output, // html body
      // };

      // transporter.sendMail(info, (error,info) => {
      //     if(error){
      //         return console.log(error);
      //     }
      //     console.log(info)
      //     res.send('sent successfully thank you !!!')

      
      // })

    //   var transport = nodemailer.createTransport({
    //     host: "smtp.mailtrap.io",
    //     port: 2525,
    //     auth: {
    //       user: "85395e426e7a79", //generated by Mailtrap
    //       pass: "88d3ccb82d94ba" //generated by Mailtrap
    //     }
    //   });

    //   var mailOptions = {
    //     from: 'pluralplu77@gmail.com',
    //     to: 'gadsprogram@gmail.com',
    //     subject: 'Nice Nodemailer test',
    //     text: 'Hey there, it’s our first message sent with Nodemailer ;) ',
    //     html: '<b>Hey there! </b><br> This is our first message sent with Nodemailer'
    // };

    //     transport.sendMail(mailOptions, (error, info) => {
    //       if (error) {
    //           return console.log(error);
    //       }
    //       // console.log('Message sent: %s', info.messageId);
    //       console.log(info)
    //       res.send('messge sent')
    // });

    let transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL,
        pass: process.env.PASSWORD
      }
    });
  
    // send mail with defined transport object
    let info = {
      from: process.env.EMAIL, // sender address
      to: "gadsprogram@gmail.com", // list of receivers
      subject: "Resume", // Subject line
      text: "reached out on resume", // plain text body
      html: output, // html body
    };

    transporter.sendMail(info, (error,info) => {
        if(error){
            return console.log(error);
        }
        console.log(info)
        res.send('sent successfully thank you !!!')
    })
  
    })



app.listen(PORT, ()=> {
    console.log('we working!!!')
})

// let transporter = nodemailer.createTransport({
//   host: 'smtp.gmail.com',
//   port: 465,
//   secure: true,
//   service: 'gmail',
//   auth: {
//         type: "OAUTH2",
//         user: process.env.USER,  //set these in your .env file
//         pass: process.env.PASS,
//         clientId: process.env.OAUTH_CLIENT_ID,
//         clientSecret: process.env.OAUTH_CLIENT_SECRET,
//         refreshToken: process.env.OAUTH_REFRESH_TOKEN,
//         accessToken: process.env.OAUTH_ACCESS_TOKEN,
//         expires: 3599
//   }
// });
